// <auto-generated />
namespace VoC.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _213123v : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_213123v));
        
        string IMigrationMetadata.Id
        {
            get { return "201611162037061_213123v"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
